spring:
  datasource:
    url: jdbc:mysql://localhost:3306/it_trainig_db?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: Sa05071992

  jpa:
    hibernate:
      ddl-auto: update
      

